/**
 * Color and style mappings for all subjects matching Figma design system.
 */
export const SUBJECT_COLOR_MAP = {
  'Math': {
    badgeBg: 'bg-[#ba704f]',
    badgeText: 'text-white',
    pillActive: 'bg-[#356F58] text-white border-[#356F58]',
    titleColor: 'text-[#ba704f]',
    circleBorder: 'border-[#ba704f]',
    dashedBorder: 'border-[#d9825b]',
    dashedText: 'text-[#ba704f]',
    dashedBg: 'bg-[#fffaf5]',
    code: 'L14',
    curriculum: 'Saxon Math',
  },
  'Phonics': {
    badgeBg: 'bg-[#558273]',
    badgeText: 'text-white',
    pillActive: 'bg-[#558273] text-white border-[#558273]',
    titleColor: 'text-[#558273]',
    circleBorder: 'border-[#558273]',
    dashedBorder: 'border-[#558273]',
    dashedText: 'text-[#558273]',
    dashedBg: 'bg-[#f0faf5]',
    code: 'L8',
    curriculum: 'All About Reading',
  },
  'Writing': {
    badgeBg: 'bg-[#e5a93c]',
    badgeText: 'text-white',
    pillActive: 'bg-[#e5a93c] text-white border-[#e5a93c]',
    titleColor: 'text-[#c2841b]',
    circleBorder: 'border-[#e5a93c]',
    dashedBorder: 'border-[#e5a93c]',
    dashedText: 'text-[#c2841b]',
    dashedBg: 'bg-[#fffdf5]',
    code: 'L5',
    curriculum: 'Writing With Ease',
  },
  'Language Arts': {
    badgeBg: 'bg-[#4f7d74]',
    badgeText: 'text-white',
    pillActive: 'bg-[#4f7d74] text-white border-[#4f7d74]',
    titleColor: 'text-[#4f7d74]',
    circleBorder: 'border-[#4f7d74]',
    dashedBorder: 'border-[#4f7d74]',
    dashedText: 'text-[#4f7d74]',
    dashedBg: 'bg-[#f0f8f6]',
    code: 'L12',
    curriculum: 'First Language Lessons',
  },
  'History': {
    badgeBg: 'bg-[#1e2a38]',
    badgeText: 'text-white',
    pillActive: 'bg-[#1e2a38] text-white border-[#1e2a38]',
    titleColor: 'text-[#1e2a38]',
    circleBorder: 'border-[#1e2a38]',
    dashedBorder: 'border-[#1e2a38]',
    dashedText: 'text-[#1e2a38]',
    dashedBg: 'bg-[#f3f5f8]',
    code: 'Ch 4',
    curriculum: 'Story of the World',
  },
  'Science': {
    badgeBg: 'bg-[#459b73]',
    badgeText: 'text-white',
    pillActive: 'bg-[#459b73] text-white border-[#459b73]',
    titleColor: 'text-[#356F58]',
    circleBorder: 'border-[#459b73]',
    dashedBorder: 'border-[#459b73]',
    dashedText: 'text-[#356F58]',
    dashedBg: 'bg-[#f0faf5]',
    code: 'Unit 2',
    curriculum: 'Building Foundations of Scientific Understanding',
  },
  'Bible / Character': {
    badgeBg: 'bg-[#70587c]',
    badgeText: 'text-white',
    pillActive: 'bg-[#70587c] text-white border-[#70587c]',
    titleColor: 'text-[#70587c]',
    circleBorder: 'border-[#70587c]',
    dashedBorder: 'border-[#70587c]',
    dashedText: 'text-[#70587c]',
    dashedBg: 'bg-[#faf5fc]',
    code: 'L3',
    curriculum: 'Leading Little Ones to God',
  },
  'AI & Coding': {
    badgeBg: 'bg-[#2d68c4]',
    badgeText: 'text-white',
    pillActive: 'bg-[#2d68c4] text-white border-[#2d68c4]',
    titleColor: 'text-[#2d68c4]',
    circleBorder: 'border-[#2d68c4]',
    dashedBorder: 'border-[#2d68c4]',
    dashedText: 'text-[#2d68c4]',
    dashedBg: 'bg-[#f0f5fc]',
    code: 'Mod 1',
    curriculum: 'Scratch Coding & Logic',
  },
  'Classical Languages': {
    badgeBg: 'bg-[#8a5d3b]',
    badgeText: 'text-white',
    pillActive: 'bg-[#8a5d3b] text-white border-[#8a5d3b]',
    titleColor: 'text-[#8a5d3b]',
    circleBorder: 'border-[#8a5d3b]',
    dashedBorder: 'border-[#8a5d3b]',
    dashedText: 'text-[#8a5d3b]',
    dashedBg: 'bg-[#faf6f2]',
    code: 'Cap I',
    curriculum: 'Song School Latin',
  },
  'Foreign Language': {
    badgeBg: 'bg-[#1d7f99]',
    badgeText: 'text-white',
    pillActive: 'bg-[#1d7f99] text-white border-[#1d7f99]',
    titleColor: 'text-[#1d7f99]',
    circleBorder: 'border-[#1d7f99]',
    dashedBorder: 'border-[#1d7f99]',
    dashedText: 'text-[#1d7f99]',
    dashedBg: 'bg-[#f0f9fb]',
    code: 'L6',
    curriculum: 'Spanish for Children',
  },
  'Logic / Thinking': {
    badgeBg: 'bg-[#386b68]',
    badgeText: 'text-white',
    pillActive: 'bg-[#386b68] text-white border-[#386b68]',
    titleColor: 'text-[#386b68]',
    circleBorder: 'border-[#386b68]',
    dashedBorder: 'border-[#386b68]',
    dashedText: 'text-[#386b68]',
    dashedBg: 'bg-[#f2f8f7]',
    code: 'Ex 2',
    curriculum: 'Mind Benders',
  },
  'Art': {
    badgeBg: 'bg-[#cf5c50]',
    badgeText: 'text-white',
    pillActive: 'bg-[#cf5c50] text-white border-[#cf5c50]',
    titleColor: 'text-[#cf5c50]',
    circleBorder: 'border-[#cf5c50]',
    dashedBorder: 'border-[#cf5c50]',
    dashedText: 'text-[#cf5c50]',
    dashedBg: 'bg-[#fcf3f2]',
    code: 'Proj 1',
    curriculum: 'Artistic Pursuits',
  },
  'Music': {
    badgeBg: 'bg-[#b49fdf]',
    badgeText: 'text-white',
    pillActive: 'bg-[#9d84d6] text-white border-[#9d84d6]',
    titleColor: 'text-[#7c3aed]',
    circleBorder: 'border-[#9d84d6]',
    dashedBorder: 'border-[#b49fdf]',
    dashedText: 'text-[#7c3aed]',
    dashedBg: 'bg-[#faf6fd]',
    code: 'Track 3',
    curriculum: 'Composer Study & Piano',
  },
  'Morning Time': {
    badgeBg: 'bg-[#d49237]',
    badgeText: 'text-white',
    pillActive: 'bg-[#d49237] text-white border-[#d49237]',
    titleColor: 'text-[#b87814]',
    circleBorder: 'border-[#d49237]',
    dashedBorder: 'border-[#d49237]',
    dashedText: 'text-[#b87814]',
    dashedBg: 'bg-[#fffaf0]',
    code: 'Daily',
    curriculum: 'Poetry & Memory Work',
  },
  'Read-Aloud': {
    badgeBg: 'bg-[#558273]',
    badgeText: 'text-white',
    pillActive: 'bg-[#558273] text-white border-[#558273]',
    titleColor: 'text-[#558273]',
    circleBorder: 'border-[#558273]',
    dashedBorder: 'border-[#558273]',
    dashedText: 'text-[#558273]',
    dashedBg: 'bg-[#f2faf4]',
    code: 'Ch 2',
    curriculum: 'Charlotte’s Web',
  },
  'Nature Study': {
    badgeBg: 'bg-[#356F58]',
    badgeText: 'text-white',
    pillActive: 'bg-[#356F58] text-white border-[#356F58]',
    titleColor: 'text-[#356F58]',
    circleBorder: 'border-[#356F58]',
    dashedBorder: 'border-[#356F58]',
    dashedText: 'text-[#356F58]',
    dashedBg: 'bg-[#eff7f2]',
    code: 'Field 1',
    curriculum: 'Handbook of Nature Study',
  },
  'Co-op': {
    badgeBg: 'bg-[#495b63]',
    badgeText: 'text-white',
    pillActive: 'bg-[#495b63] text-white border-[#495b63]',
    titleColor: 'text-[#495b63]',
    circleBorder: 'border-[#495b63]',
    dashedBorder: 'border-[#495b63]',
    dashedText: 'text-[#495b63]',
    dashedBg: 'bg-[#f2f5f7]',
    code: 'Session',
    curriculum: 'Weekly Homeschool Co-op',
  },
  'Review': {
    badgeBg: 'bg-[#ba704f]',
    badgeText: 'text-white',
    pillActive: 'bg-[#ba704f] text-white border-[#ba704f]',
    titleColor: 'text-[#ba704f]',
    circleBorder: 'border-[#ba704f]',
    dashedBorder: 'border-[#d9825b]',
    dashedText: 'text-[#ba704f]',
    dashedBg: 'bg-[#fffaf5]',
    code: 'Quiz 1',
    curriculum: 'Weekly Progress Review',
  },
  'Physical Education': {
    badgeBg: 'bg-[#c45535]',
    badgeText: 'text-white',
    pillActive: 'bg-[#c45535] text-white border-[#c45535]',
    titleColor: 'text-[#c45535]',
    circleBorder: 'border-[#c45535]',
    dashedBorder: 'border-[#c45535]',
    dashedText: 'text-[#c45535]',
    dashedBg: 'bg-[#fcf4f2]',
    code: 'Active',
    curriculum: 'Outdoor Play & Gymnastics',
  },
};

export function getSubjectStyle(subjectName) {
  return (
    SUBJECT_COLOR_MAP[subjectName] || {
      badgeBg: 'bg-[#ba704f]',
      badgeText: 'text-white',
      pillActive: 'bg-[#356F58] text-white border-[#356F58]',
      titleColor: 'text-[#ba704f]',
      circleBorder: 'border-[#ba704f]',
      dashedBorder: 'border-[#d9825b]',
      dashedText: 'text-[#ba704f]',
      dashedBg: 'bg-[#fffaf5]',
      code: 'L1',
      curriculum: `${subjectName} Curriculum`,
    }
  );
}
